Visual Studio Code (1.76.2, undefined, desktop)
Jupyter Extension Version: 2023.2.1200692131.
Python Extension Version: 2023.4.1.
Workspace folder /home/hadi/Desktop
warn 18:19:32.338: Exception while attempting zmq : /snap/core/current/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/hadi/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/node_modules/zeromq/prebuilds/linux-x64/electron.napi.glibc.node)
User belongs to experiment group 'jupyterEnhancedDataViewer'
User belongs to experiment group 'jupyterTestcf'
info 18:19:32.838: Attempting to start a server because of preload conditions ...
info 18:19:33.036: LSP Notebooks experiment is enabled
info 18:19:33.037: Checking for server existence.
warn 18:19:36.655: Failed to get activated env vars with python /bin/python3 in 2962ms
warn 18:19:36.659: Failed to get activated env vars with python /bin/python3 in 2966ms
warn 18:19:36.660: Failed to get activated env vars with python /bin/python3 in 2966ms
info 18:19:36.857: Process Execution: > /bin/python3 -c "import site;print("USER_BASE_VALUE");print(site.USER_SITE);print("USER_BASE_VALUE");"
> /bin/python3 -c "import site;print("USER_BASE_VALUE");print(site.USER_SITE);print("USER_BASE_VALUE");"
info 18:19:36.919: Process Execution: > /bin/python3 -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /bin/python3 -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 18:19:36.933: Process Execution: > /bin/python3 -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /bin/python3 -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 18:19:36.952: Process Execution: > /bin/python3 -m pip list
> /bin/python3 -m pip list
warn 18:19:40.233: Failed to get activated env vars with python /bin/python3 in 105ms
info 18:19:40.255: Process Execution: > /bin/python3 -m jupyter kernelspec --version
> /bin/python3 -m jupyter kernelspec --version
info 18:19:41.965: Connecting to server
info 18:19:41.965: Launching server
info 18:19:41.966: Starting Notebook
info 18:19:41.988: Generating custom default config at /tmp/f23dea37-4b21-4097-b2ce-108804386ffc/jupyter_notebook_config.py
Starting Jupyter from /bin/python3 with arguments --no-browser --notebook-dir="/home/hadi/Desktop" --config=/tmp/f23dea37-4b21-4097-b2ce-108804386ffc/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
warn 18:19:42.016: Failed to get activated env vars with python /bin/python3 in 52ms
warn 18:19:42.019: Failed to get activated env vars with python /bin/python3 in 55ms
warn 18:19:42.025: Failed to get activated env vars with python /bin/python3 in 36ms
warn 18:19:42.068: Failed to get activated env vars with python /bin/python3 in 40ms
info 18:19:42.092: Process Execution: > /bin/python3 -m jupyter notebook --no-browser --notebook-dir="/home/hadi/Desktop" --config=/tmp/f23dea37-4b21-4097-b2ce-108804386ffc/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
> /bin/python3 -m jupyter notebook --no-browser --notebook-dir="/home/hadi/Desktop" --config=/tmp/f23dea37-4b21-4097-b2ce-108804386ffc/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
/home/hadi/.local/lib/python3.10/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/home/hadi/Desktop' instead of '"/home/hadi/Desktop"' if you require traitlets >=5.
  warn(

  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_|
                       
Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.

https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

Please note that updating to Notebook 7 might break some of your extensions.

[I 18:19:47.447 NotebookApp] Serving notebooks from local directory: /home/hadi/Desktop
[I 18:19:47.447 NotebookApp] Jupyter Notebook 6.5.3 is running at:
[I 18:19:47.447 NotebookApp] http://localhost:8888/?token=ccfe4235759a1172ad5b76453983b5ef62f96511cf344c15
[I 18:19:47.447 NotebookApp]  or http://127.0.0.1:8888/?token=ccfe4235759a1172ad5b76453983b5ef62f96511cf344c15
[I 18:19:47.447 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
warn 18:19:47.459: Failed to get activated env vars with python /bin/python3 in 11ms
info 18:19:47.477: Process Execution: > /bin/python3 ~/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> /bin/python3 ~/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/pythonFiles/vscode_datascience_helpers/getServerInfo.py
[C 18:19:47.471 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/hadi/.local/share/jupyter/runtime/nbserver-23950-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=ccfe4235759a1172ad5b76453983b5ef62f96511cf344c15
     or http://127.0.0.1:8888/?token=ccfe4235759a1172ad5b76453983b5ef62f96511cf344c15
warn 18:19:47.487: Failed to get activated env vars with python /bin/python3 in 8ms
info 18:19:47.506: Process Execution: > /bin/python3 ~/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> /bin/python3 ~/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/pythonFiles/vscode_datascience_helpers/getServerInfo.py
info 18:19:48.625: Connecting local server kernel http://localhost:8888/
info 18:19:48.626: Creating server with url : http://localhost:8888/
info 18:19:48.669: Server started.
info 18:22:41.479: Starting interactive window for resource '/home/hadi/Desktop/earthquake_proj/data_modifier.py' with controller '.jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1./bin/python3./bin/python3.-m#ipykernel_launcher (Interactive)'
info 18:22:41.542: Attempting to start a server because of preload conditions ...
info 18:22:43.284: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1./bin/python3./bin/python3.-m#ipykernel_launcher (Python Path: , EnvType: Unknown, EnvName: '', Version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]) for '/Interactive-1.interactive' (disableUI=false)
[I 18:22:43.302 NotebookApp] Creating new notebook in /earthquake_proj
info 18:22:44.074: installMissingDependencies /bin/python3, ui.disabled=false for resource '/home/hadi/Desktop/earthquake_proj/data_modifier.py'
warn 18:22:44.099: Failed to get activated env vars with python /bin/python3 in 22ms
info 18:22:44.119: Process Execution: > /bin/python3 -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /bin/python3 -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 18:22:44.384: Spec argv[0] updated from '/bin/python3' to '/bin/python3'
warn 18:22:44.395: Failed to get activated env vars with python /bin/python3 in 10ms
[I 18:22:44.500 NotebookApp] Kernel started: 00d51348-4472-4e88-9325-416ac06f779b, name: pythonjvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1
[W 18:22:44.524 NotebookApp] delete /earthquake_proj/data_modifier.py-jvsc-a0af376c-8462-454c-a91e-31fa67e9a569a446faed-2073-4b93-8093-f16a65fa20e2.ipynb
info 18:22:53.560: Started session for kernel startUsingPythonInterpreter:.jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1./bin/python3./bin/python3.-m#ipykernel_launcher
[E 18:22:54.070 NotebookApp] Uncaught exception in ZMQStream callback
    Traceback (most recent call last):
      File "/home/hadi/.local/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
        f = callback(*args, **kwargs)
      File "/home/hadi/.local/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 308, in stream_callback
        return callback(self, msg)
      File "/home/hadi/.local/lib/python3.10/site-packages/notebook/services/kernels/handlers.py", line 572, in _on_zmq_reply
        super()._on_zmq_reply(stream, msg)
      File "/home/hadi/.local/lib/python3.10/site-packages/notebook/base/zmqhandlers.py", line 256, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/hadi/.local/lib/python3.10/site-packages/tornado/websocket.py", line 339, in write_message
        return self.ws_connection.write_message(message, binary=binary)
      File "/home/hadi/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1086, in write_message
        fut = self._write_frame(True, opcode, message, flags=flags)
      File "/home/hadi/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1061, in _write_frame
        return self.stream.write(frame)
      File "/home/hadi/.local/lib/python3.10/site-packages/tornado/iostream.py", line 546, in write
        self._handle_write()
      File "/home/hadi/.local/lib/python3.10/site-packages/tornado/iostream.py", line 976, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/home/hadi/.local/lib/python3.10/site-packages/tornado/iostream.py", line 182, in advance
        assert 0 < size <= self._size
    AssertionError
[E 18:22:54.214 NotebookApp] Uncaught exception in zmqstream callback
    Traceback (most recent call last):
      File "/home/hadi/.local/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 621, in _handle_events
        self._handle_recv()
      File "/home/hadi/.local/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 650, in _handle_recv
        self._run_callback(callback, msg)
      File "/home/hadi/.local/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
        f = callback(*args, **kwargs)
      File "/home/hadi/.local/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 308, in stream_callback
        return callback(self, msg)
      File "/home/hadi/.local/lib/python3.10/site-packages/notebook/services/kernels/handlers.py", line 572, in _on_zmq_reply
        super()._on_zmq_reply(stream, msg)
      File "/home/hadi/.local/lib/python3.10/site-packages/notebook/base/zmqhandlers.py", line 256, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/hadi/.local/lib/python3.10/site-packages/tornado/websocket.py", line 339, in write_message
        return self.ws_connection.write_message(message, binary=binary)
      File "/home/hadi/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1086, in write_message
        fut = self._write_frame(True, opcode, message, flags=flags)
      File "/home/hadi/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1061, in _write_frame
        return self.stream.write(frame)
      File "/home/hadi/.local/lib/python3.10/site-packages/tornado/iostream.py", line 546, in write
        self._handle_write()
      File "/home/hadi/.local/lib/python3.10/site-packages/tornado/iostream.py", line 976, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/home/hadi/.local/lib/python3.10/site-packages/tornado/iostream.py", line 182, in advance
        assert 0 < size <= self._size
    AssertionError
Exception in callback BaseAsyncIOLoop._handle_events(34, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(34, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/hadi/.local/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 206, in _handle_events
    handler_func(fileobj, events)
  File "/home/hadi/.local/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 621, in _handle_events
    self._handle_recv()
  File "/home/hadi/.local/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 650, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/hadi/.local/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/home/hadi/.local/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 308, in stream_callback
    return callback(self, msg)
  File "/home/hadi/.local/lib/python3.10/site-packages/notebook/services/kernels/handlers.py", line 572, in _on_zmq_reply
    super()._on_zmq_reply(stream, msg)
  File "/home/hadi/.local/lib/python3.10/site-packages/notebook/base/zmqhandlers.py", line 256, in _on_zmq_reply
    self.write_message(msg, binary=isinstance(msg, bytes))
  File "/home/hadi/.local/lib/python3.10/site-packages/tornado/websocket.py", line 339, in write_message
    return self.ws_connection.write_message(message, binary=binary)
  File "/home/hadi/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1086, in write_message
    fut = self._write_frame(True, opcode, message, flags=flags)
  File "/home/hadi/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1061, in _write_frame
    return self.stream.write(frame)
  File "/home/hadi/.local/lib/python3.10/site-packages/tornado/iostream.py", line 546, in write
    self._handle_write()
  File "/home/hadi/.local/lib/python3.10/site-packages/tornado/iostream.py", line 976, in _handle_write
    self._write_buffer.advance(num_bytes)
  File "/home/hadi/.local/lib/python3.10/site-packages/tornado/iostream.py", line 182, in advance
    assert 0 < size <= self._size
AssertionError
warn 18:22:54.638: Failed to get activated env vars with python /bin/python3 in 580ms
info 18:22:54.694: Process Execution: > /bin/python3 ~/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/pythonFiles/printJupyterDataDir.py
> /bin/python3 ~/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/pythonFiles/printJupyterDataDir.py
info 18:30:21.145: Shutting down notebooks for a02c158c-2f99-404f-ac1e-34c3f3f497fe
info 18:30:21.145: Disposing HostJupyterExecution 1ff9e5cd-3d3a-486f-8e4f-6e321dcd928a
info 18:30:21.146: Dispose Kernel '/Interactive-1.interactive' associated with '/home/hadi/Desktop/earthquake_proj/data_modifier.py'
info 18:30:21.152: Disposing HostJupyterExecution 1ff9e5cd-3d3a-486f-8e4f-6e321dcd928a
info 18:30:21.176: Dispose Kernel '/Interactive-1.interactive' associated with '/home/hadi/Desktop/earthquake_proj/data_modifier.py'
[C 18:30:21.157 NotebookApp] received signal 15, stopping
[I 18:30:21.157 NotebookApp] Shutting down 1 kernel
[I 18:30:21.158 NotebookApp] Kernel shutdown: 00d51348-4472-4e88-9325-416ac06f779b
error 18:30:22.153: Error in execution (get message for cell) [Error: Canceled future for execute_request message before replies were done
	at t.KernelShellFutureHandler.dispose (/home/hadi/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:2:33213)
	at /home/hadi/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:2:27432
	at Map.forEach (<anonymous>)
	at v._clearKernelState (/home/hadi/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:2:27417)
	at v.dispose (/home/hadi/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:2:20873)
	at t.SessionConnection.dispose (/home/hadi/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:2:72886)
	at pg.shutdownSession (/home/hadi/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:17:121798)
	at async pg.shutdownImplementation (/home/hadi/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:17:122024)
	at async pg.dispose (/home/hadi/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:17:116492)
	at async Promise.all (index 1)
	at async /home/hadi/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:17:292872]
warn 18:30:22.157: DataScience Error [Error: Canceled future for execute_request message before replies were done
	at t.KernelShellFutureHandler.dispose (/home/hadi/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:2:33213)
	at /home/hadi/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:2:27432
	at Map.forEach (<anonymous>)
	at v._clearKernelState (/home/hadi/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:2:27417)
	at v.dispose (/home/hadi/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:2:20873)
	at t.SessionConnection.dispose (/home/hadi/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:2:72886)
	at pg.shutdownSession (/home/hadi/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:17:121798)
	at async pg.shutdownImplementation (/home/hadi/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:17:122024)
	at async pg.dispose (/home/hadi/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:17:116492)
	at async Promise.all (index 1)
	at async /home/hadi/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:17:292872]
